name = "find-number-worker"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[durable_objects.bindings]]
name = "MATCH_QUEUE"
class_name = "MatchQueue"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom", "MatchQueue"]

[[d1_databases]]
binding = "DB"
database_name = "find-number-db"
database_id = "70d00ce3-2c7b-44d1-803c-957dd54537e0"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "6ef23d8444964d3b8a790c64372c25ea"

[dev]
port = 8787
